manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cosmo-zmk
      url-base: https://github.com/m-alexeev/
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: cosmo-zmk
      remote: cosmo-zmk
      revision: main
  self:
    path: config
